[2023-11-07T16:55:38.737+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ps_etl.ps_extract manual__2023-11-07T16:55:35.641878+00:00 [queued]>
[2023-11-07T16:55:38.746+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ps_etl.ps_extract manual__2023-11-07T16:55:35.641878+00:00 [queued]>
[2023-11-07T16:55:38.747+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-11-07T16:55:38.759+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): ps_extract> on 2023-11-07 16:55:35.641878+00:00
[2023-11-07T16:55:38.763+0000] {standard_task_runner.py:57} INFO - Started process 62 to run task
[2023-11-07T16:55:38.767+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'ps_etl', 'ps_extract', 'manual__2023-11-07T16:55:35.641878+00:00', '--job-id', '140', '--raw', '--subdir', 'DAGS_FOLDER/ps_etl.py', '--cfg-path', '/tmp/tmp9v9umsnj']
[2023-11-07T16:55:38.771+0000] {standard_task_runner.py:85} INFO - Job 140: Subtask ps_extract
[2023-11-07T16:55:38.814+0000] {task_command.py:416} INFO - Running <TaskInstance: ps_etl.ps_extract manual__2023-11-07T16:55:35.641878+00:00 [running]> on host 19429b98c313
[2023-11-07T16:55:38.890+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ps_etl' AIRFLOW_CTX_TASK_ID='ps_extract' AIRFLOW_CTX_EXECUTION_DATE='2023-11-07T16:55:35.641878+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-07T16:55:35.641878+00:00'
[2023-11-07T16:55:38.897+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/compat/_optional.py", line 142, in import_optional_dependency
    module = importlib.import_module(name)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'openpyxl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ps_extract.py", line 25, in extract
    xls = pd.ExcelFile(file_path)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/excel/_base.py", line 1513, in __init__
    self._reader = self._engines[engine](self._io, storage_options=storage_options)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/excel/_openpyxl.py", line 548, in __init__
    import_optional_dependency("openpyxl")
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/compat/_optional.py", line 145, in import_optional_dependency
    raise ImportError(msg)
ImportError: Missing optional dependency 'openpyxl'.  Use pip or conda to install openpyxl.
[2023-11-07T16:55:38.909+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=ps_etl, task_id=ps_extract, execution_date=20231107T165535, start_date=20231107T165538, end_date=20231107T165538
[2023-11-07T16:55:38.924+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 140 for task ps_extract (Missing optional dependency 'openpyxl'.  Use pip or conda to install openpyxl.; 62)
[2023-11-07T16:55:38.940+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-07T16:55:38.978+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
