[2023-11-07T04:53:04.476+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ps_etl.load_to_snowflake_table manual__2023-11-07T04:52:53.478550+00:00 [queued]>
[2023-11-07T04:53:04.488+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ps_etl.load_to_snowflake_table manual__2023-11-07T04:52:53.478550+00:00 [queued]>
[2023-11-07T04:53:04.488+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-11-07T04:53:04.503+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): load_to_snowflake_table> on 2023-11-07 04:52:53.478550+00:00
[2023-11-07T04:53:04.510+0000] {standard_task_runner.py:57} INFO - Started process 2300 to run task
[2023-11-07T04:53:04.515+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'ps_etl', 'load_to_snowflake_table', 'manual__2023-11-07T04:52:53.478550+00:00', '--job-id', '95', '--raw', '--subdir', 'DAGS_FOLDER/ps_etl.py', '--cfg-path', '/tmp/tmplw4g2j7p']
[2023-11-07T04:53:04.520+0000] {standard_task_runner.py:85} INFO - Job 95: Subtask load_to_snowflake_table
[2023-11-07T04:53:04.573+0000] {task_command.py:416} INFO - Running <TaskInstance: ps_etl.load_to_snowflake_table manual__2023-11-07T04:52:53.478550+00:00 [running]> on host d2308b8de1b3
[2023-11-07T04:53:04.639+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ps_etl' AIRFLOW_CTX_TASK_ID='load_to_snowflake_table' AIRFLOW_CTX_EXECUTION_DATE='2023-11-07T04:52:53.478550+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-07T04:52:53.478550+00:00'
[2023-11-07T04:53:04.650+0000] {base.py:73} INFO - Using connection ID 'snowflake_default' for task execution.
[2023-11-07T04:53:04.651+0000] {connection.py:329} INFO - Snowflake Connector for Python Version: 3.2.1, Python Version: 3.8.18, Platform: Linux-6.4.16-linuxkit-x86_64-with-glibc2.2.5
[2023-11-07T04:53:04.652+0000] {connection.py:1069} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2023-11-07T04:53:04.652+0000] {connection.py:1087} INFO - Setting use_openssl_only mode to False
[2023-11-07T04:53:05.446+0000] {cursor.py:804} INFO - query: [ALTER SESSION SET autocommit=False]
[2023-11-07T04:53:05.584+0000] {cursor.py:817} INFO - query execution done
[2023-11-07T04:53:05.585+0000] {cursor.py:959} INFO - Number of results in first chunk: 1
[2023-11-07T04:53:05.586+0000] {sql.py:418} INFO - Running statement: USE SCHEMA PUBLIC;, parameters: None
[2023-11-07T04:53:05.587+0000] {cursor.py:804} INFO - query: [USE SCHEMA PUBLIC;]
[2023-11-07T04:53:05.746+0000] {cursor.py:817} INFO - query execution done
[2023-11-07T04:53:05.747+0000] {cursor.py:959} INFO - Number of results in first chunk: 1
[2023-11-07T04:53:05.748+0000] {sql.py:427} INFO - Rows affected: 1
[2023-11-07T04:53:05.748+0000] {snowflake.py:400} INFO - Rows affected: 1
[2023-11-07T04:53:05.749+0000] {snowflake.py:401} INFO - Snowflake query id: 01b029a5-0004-d155-0000-0001ead73375
[2023-11-07T04:53:05.750+0000] {sql.py:418} INFO - Running statement: CREATE OR REPLACE TABLE LOYALTY_EARNED_HOURLY (
            date TIMESTAMP,
            userId VARCHAR(20),
            country CHAR(2),
            total_lp_earned INT
         );, parameters: None
[2023-11-07T04:53:05.751+0000] {cursor.py:804} INFO - query: [CREATE OR REPLACE TABLE LOYALTY_EARNED_HOURLY ( date TIMESTAMP, userId VARCHAR(2...]
[2023-11-07T04:53:06.090+0000] {cursor.py:817} INFO - query execution done
[2023-11-07T04:53:06.091+0000] {cursor.py:959} INFO - Number of results in first chunk: 1
[2023-11-07T04:53:06.092+0000] {sql.py:427} INFO - Rows affected: 1
[2023-11-07T04:53:06.092+0000] {snowflake.py:400} INFO - Rows affected: 1
[2023-11-07T04:53:06.093+0000] {snowflake.py:401} INFO - Snowflake query id: 01b029a5-0004-d145-0000-0001ead7a089
[2023-11-07T04:53:06.094+0000] {sql.py:418} INFO - Running statement: CREATE OR REPLACE TABLE PURCHASES (
            date TIMESTAMP,
            userId VARCHAR(20),
            price_in_usd DECIMAL(10, 2),
            transaction_id VARCHAR(36)
         );, parameters: None
[2023-11-07T04:53:06.095+0000] {cursor.py:804} INFO - query: [CREATE OR REPLACE TABLE PURCHASES ( date TIMESTAMP, userId VARCHAR(20), price_in...]
[2023-11-07T04:53:06.433+0000] {cursor.py:817} INFO - query execution done
[2023-11-07T04:53:06.434+0000] {cursor.py:959} INFO - Number of results in first chunk: 1
[2023-11-07T04:53:06.435+0000] {sql.py:427} INFO - Rows affected: 1
[2023-11-07T04:53:06.435+0000] {snowflake.py:400} INFO - Rows affected: 1
[2023-11-07T04:53:06.436+0000] {snowflake.py:401} INFO - Snowflake query id: 01b029a5-0004-d180-0000-0001ead7b09d
[2023-11-07T04:53:06.437+0000] {cursor.py:804} INFO - query: [COMMIT]
[2023-11-07T04:53:06.584+0000] {cursor.py:817} INFO - query execution done
[2023-11-07T04:53:06.585+0000] {cursor.py:959} INFO - Number of results in first chunk: 1
[2023-11-07T04:53:06.586+0000] {connection.py:659} INFO - closed
[2023-11-07T04:53:06.701+0000] {connection.py:665} INFO - No async queries seem to be running, deleting session
[2023-11-07T04:53:06.899+0000] {logging_mixin.py:151} INFO - copy file Loyalty_Earned_Hourly_Data_Set/processed_leh_2023-11-07-04-52-55.csv
[2023-11-07T04:53:06.906+0000] {base.py:73} INFO - Using connection ID 'snowflake_default' for task execution.
[2023-11-07T04:53:06.907+0000] {connection.py:329} INFO - Snowflake Connector for Python Version: 3.2.1, Python Version: 3.8.18, Platform: Linux-6.4.16-linuxkit-x86_64-with-glibc2.2.5
[2023-11-07T04:53:06.907+0000] {connection.py:1069} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2023-11-07T04:53:07.460+0000] {cursor.py:804} INFO - query: [ALTER SESSION SET autocommit=False]
[2023-11-07T04:53:07.621+0000] {cursor.py:817} INFO - query execution done
[2023-11-07T04:53:07.622+0000] {cursor.py:959} INFO - Number of results in first chunk: 1
[2023-11-07T04:53:07.622+0000] {sql.py:418} INFO - Running statement: COPY INTO LOYALTY_EARNED_HOURLY
            FROM s3://playstudios_processed_data/Loyalty_Earned_Hourly_Data_Set/Loyalty_Earned_Hourly_Data_Set/processed_leh_2023-11-07-04-52-55.csv
            FILE_FORMAT = (TYPE = CSV), parameters: None
[2023-11-07T04:53:07.623+0000] {cursor.py:804} INFO - query: [COPY INTO LOYALTY_EARNED_HOURLY FROM s3://playstudios_processed_data/Loyalty_Ear...]
[2023-11-07T04:53:08.654+0000] {cursor.py:817} INFO - query execution done
[2023-11-07T04:53:08.661+0000] {connection.py:659} INFO - closed
[2023-11-07T04:53:08.773+0000] {connection.py:665} INFO - No async queries seem to be running, deleting session
[2023-11-07T04:53:08.881+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ps_load.py", line 51, in run_snowflake_load_sql
    snowflake_hook.run(copy_into_command)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 388, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 423, in _run_command
    cur.execute(sql_statement)
  File "/home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/cursor.py", line 908, in execute
    Error.errorhandler_wrapper(self.connection, self, error_class, errvalue)
  File "/home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/errors.py", line 290, in errorhandler_wrapper
    handed_over = Error.hand_to_other_handler(
  File "/home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/errors.py", line 345, in hand_to_other_handler
    cursor.errorhandler(connection, cursor, error_class, error_value)
  File "/home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/errors.py", line 221, in default_errorhandler
    raise error_class(
snowflake.connector.errors.ProgrammingError: 091017 (22000): 01b029a5-0004-d114-0000-0001ead783c9: S3 bucket 'playstudios_processed_data' does not exist or not authorized.
[2023-11-07T04:53:08.890+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=ps_etl, task_id=load_to_snowflake_table, execution_date=20231107T045253, start_date=20231107T045304, end_date=20231107T045308
[2023-11-07T04:53:08.903+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 95 for task load_to_snowflake_table (091017 (22000): 01b029a5-0004-d114-0000-0001ead783c9: S3 bucket 'playstudios_processed_data' does not exist or not authorized.; 2300)
[2023-11-07T04:53:08.917+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-07T04:53:08.933+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
