[2023-11-07T16:39:43.788+0000] {processor.py:157} INFO - Started process (PID=43) to work on /opt/airflow/dags/ps_etl/ps_etl.py
[2023-11-07T16:39:43.790+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ps_etl/ps_etl.py for tasks to queue
[2023-11-07T16:39:43.792+0000] {logging_mixin.py:151} INFO - [2023-11-07T16:39:43.792+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ps_etl/ps_etl.py
[2023-11-07T16:39:43.800+0000] {logging_mixin.py:151} INFO - [2023-11-07T16:39:43.798+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ps_etl/ps_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ps_etl/ps_etl.py", line 6, in <module>
    from ps_extract import extract
ModuleNotFoundError: No module named 'ps_extract'
[2023-11-07T16:39:43.801+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ps_etl/ps_etl.py
[2023-11-07T16:39:43.820+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ps_etl/ps_etl.py took 0.035 seconds
[2023-11-07T16:40:13.964+0000] {processor.py:157} INFO - Started process (PID=51) to work on /opt/airflow/dags/ps_etl/ps_etl.py
[2023-11-07T16:40:13.965+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ps_etl/ps_etl.py for tasks to queue
[2023-11-07T16:40:13.968+0000] {logging_mixin.py:151} INFO - [2023-11-07T16:40:13.967+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ps_etl/ps_etl.py
[2023-11-07T16:40:13.975+0000] {logging_mixin.py:151} INFO - [2023-11-07T16:40:13.973+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ps_etl/ps_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ps_etl/ps_etl.py", line 6, in <module>
    from ps_extract import extract
ModuleNotFoundError: No module named 'ps_extract'
[2023-11-07T16:40:13.976+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ps_etl/ps_etl.py
[2023-11-07T16:40:13.993+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ps_etl/ps_etl.py took 0.033 seconds
[2023-11-07T16:40:44.131+0000] {processor.py:157} INFO - Started process (PID=59) to work on /opt/airflow/dags/ps_etl/ps_etl.py
[2023-11-07T16:40:44.132+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ps_etl/ps_etl.py for tasks to queue
[2023-11-07T16:40:44.135+0000] {logging_mixin.py:151} INFO - [2023-11-07T16:40:44.135+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ps_etl/ps_etl.py
[2023-11-07T16:40:44.142+0000] {logging_mixin.py:151} INFO - [2023-11-07T16:40:44.141+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ps_etl/ps_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ps_etl/ps_etl.py", line 6, in <module>
    from ps_extract import extract
ModuleNotFoundError: No module named 'ps_extract'
[2023-11-07T16:40:44.143+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ps_etl/ps_etl.py
[2023-11-07T16:40:44.161+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ps_etl/ps_etl.py took 0.034 seconds
[2023-11-07T16:41:14.290+0000] {processor.py:157} INFO - Started process (PID=67) to work on /opt/airflow/dags/ps_etl/ps_etl.py
[2023-11-07T16:41:14.292+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ps_etl/ps_etl.py for tasks to queue
[2023-11-07T16:41:14.294+0000] {logging_mixin.py:151} INFO - [2023-11-07T16:41:14.294+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ps_etl/ps_etl.py
[2023-11-07T16:41:14.300+0000] {logging_mixin.py:151} INFO - [2023-11-07T16:41:14.299+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ps_etl/ps_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ps_etl/ps_etl.py", line 6, in <module>
    from ps_extract import extract
ModuleNotFoundError: No module named 'ps_extract'
[2023-11-07T16:41:14.301+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ps_etl/ps_etl.py
[2023-11-07T16:41:14.318+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ps_etl/ps_etl.py took 0.031 seconds
[2023-11-07T16:41:44.461+0000] {processor.py:157} INFO - Started process (PID=75) to work on /opt/airflow/dags/ps_etl/ps_etl.py
[2023-11-07T16:41:44.462+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ps_etl/ps_etl.py for tasks to queue
[2023-11-07T16:41:44.465+0000] {logging_mixin.py:151} INFO - [2023-11-07T16:41:44.464+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ps_etl/ps_etl.py
[2023-11-07T16:41:44.471+0000] {logging_mixin.py:151} INFO - [2023-11-07T16:41:44.470+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ps_etl/ps_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ps_etl/ps_etl.py", line 6, in <module>
    from ps_extract import extract
ModuleNotFoundError: No module named 'ps_extract'
[2023-11-07T16:41:44.472+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ps_etl/ps_etl.py
[2023-11-07T16:41:44.523+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ps_etl/ps_etl.py took 0.065 seconds
[2023-11-07T16:42:14.629+0000] {processor.py:157} INFO - Started process (PID=83) to work on /opt/airflow/dags/ps_etl/ps_etl.py
[2023-11-07T16:42:14.630+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ps_etl/ps_etl.py for tasks to queue
[2023-11-07T16:42:14.632+0000] {logging_mixin.py:151} INFO - [2023-11-07T16:42:14.632+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ps_etl/ps_etl.py
[2023-11-07T16:42:14.639+0000] {logging_mixin.py:151} INFO - [2023-11-07T16:42:14.637+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ps_etl/ps_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ps_etl/ps_etl.py", line 6, in <module>
    from ps_extract import extract
ModuleNotFoundError: No module named 'ps_extract'
[2023-11-07T16:42:14.639+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ps_etl/ps_etl.py
[2023-11-07T16:42:14.658+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ps_etl/ps_etl.py took 0.032 seconds
[2023-11-07T16:42:44.816+0000] {processor.py:157} INFO - Started process (PID=91) to work on /opt/airflow/dags/ps_etl/ps_etl.py
[2023-11-07T16:42:44.817+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ps_etl/ps_etl.py for tasks to queue
[2023-11-07T16:42:44.820+0000] {logging_mixin.py:151} INFO - [2023-11-07T16:42:44.819+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ps_etl/ps_etl.py
[2023-11-07T16:42:44.827+0000] {logging_mixin.py:151} INFO - [2023-11-07T16:42:44.825+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ps_etl/ps_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ps_etl/ps_etl.py", line 6, in <module>
    from ps_extract import extract
ModuleNotFoundError: No module named 'ps_extract'
[2023-11-07T16:42:44.827+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ps_etl/ps_etl.py
[2023-11-07T16:42:44.846+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ps_etl/ps_etl.py took 0.034 seconds
[2023-11-07T16:43:14.979+0000] {processor.py:157} INFO - Started process (PID=99) to work on /opt/airflow/dags/ps_etl/ps_etl.py
[2023-11-07T16:43:14.979+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ps_etl/ps_etl.py for tasks to queue
[2023-11-07T16:43:14.982+0000] {logging_mixin.py:151} INFO - [2023-11-07T16:43:14.981+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ps_etl/ps_etl.py
[2023-11-07T16:43:14.988+0000] {logging_mixin.py:151} INFO - [2023-11-07T16:43:14.986+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ps_etl/ps_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ps_etl/ps_etl.py", line 6, in <module>
    from ps_extract import extract
ModuleNotFoundError: No module named 'ps_extract'
[2023-11-07T16:43:14.989+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ps_etl/ps_etl.py
[2023-11-07T16:43:15.007+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ps_etl/ps_etl.py took 0.031 seconds
[2023-11-07T16:43:45.149+0000] {processor.py:157} INFO - Started process (PID=107) to work on /opt/airflow/dags/ps_etl/ps_etl.py
[2023-11-07T16:43:45.150+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ps_etl/ps_etl.py for tasks to queue
[2023-11-07T16:43:45.152+0000] {logging_mixin.py:151} INFO - [2023-11-07T16:43:45.152+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ps_etl/ps_etl.py
[2023-11-07T16:43:45.158+0000] {logging_mixin.py:151} INFO - [2023-11-07T16:43:45.157+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ps_etl/ps_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ps_etl/ps_etl.py", line 6, in <module>
    from ps_extract import extract
ModuleNotFoundError: No module named 'ps_extract'
[2023-11-07T16:43:45.159+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ps_etl/ps_etl.py
[2023-11-07T16:43:45.177+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ps_etl/ps_etl.py took 0.031 seconds
[2023-11-07T16:44:15.300+0000] {processor.py:157} INFO - Started process (PID=115) to work on /opt/airflow/dags/ps_etl/ps_etl.py
[2023-11-07T16:44:15.301+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ps_etl/ps_etl.py for tasks to queue
[2023-11-07T16:44:15.304+0000] {logging_mixin.py:151} INFO - [2023-11-07T16:44:15.303+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ps_etl/ps_etl.py
[2023-11-07T16:44:15.310+0000] {logging_mixin.py:151} INFO - [2023-11-07T16:44:15.309+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ps_etl/ps_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ps_etl/ps_etl.py", line 6, in <module>
    from ps_extract import extract
ModuleNotFoundError: No module named 'ps_extract'
[2023-11-07T16:44:15.311+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ps_etl/ps_etl.py
[2023-11-07T16:44:15.331+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ps_etl/ps_etl.py took 0.034 seconds
[2023-11-07T16:44:45.496+0000] {processor.py:157} INFO - Started process (PID=123) to work on /opt/airflow/dags/ps_etl/ps_etl.py
[2023-11-07T16:44:45.497+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ps_etl/ps_etl.py for tasks to queue
[2023-11-07T16:44:45.500+0000] {logging_mixin.py:151} INFO - [2023-11-07T16:44:45.499+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ps_etl/ps_etl.py
[2023-11-07T16:44:45.507+0000] {logging_mixin.py:151} INFO - [2023-11-07T16:44:45.505+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ps_etl/ps_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ps_etl/ps_etl.py", line 6, in <module>
    from ps_extract import extract
ModuleNotFoundError: No module named 'ps_extract'
[2023-11-07T16:44:45.507+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ps_etl/ps_etl.py
[2023-11-07T16:44:45.528+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ps_etl/ps_etl.py took 0.036 seconds
[2023-11-07T16:45:15.663+0000] {processor.py:157} INFO - Started process (PID=131) to work on /opt/airflow/dags/ps_etl/ps_etl.py
[2023-11-07T16:45:15.664+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ps_etl/ps_etl.py for tasks to queue
[2023-11-07T16:45:15.667+0000] {logging_mixin.py:151} INFO - [2023-11-07T16:45:15.666+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ps_etl/ps_etl.py
[2023-11-07T16:45:15.673+0000] {logging_mixin.py:151} INFO - [2023-11-07T16:45:15.671+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ps_etl/ps_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ps_etl/ps_etl.py", line 6, in <module>
    from ps_extract import extract
ModuleNotFoundError: No module named 'ps_extract'
[2023-11-07T16:45:15.674+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ps_etl/ps_etl.py
[2023-11-07T16:45:15.692+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ps_etl/ps_etl.py took 0.033 seconds
[2023-11-07T16:45:45.819+0000] {processor.py:157} INFO - Started process (PID=139) to work on /opt/airflow/dags/ps_etl/ps_etl.py
[2023-11-07T16:45:45.820+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ps_etl/ps_etl.py for tasks to queue
[2023-11-07T16:45:45.822+0000] {logging_mixin.py:151} INFO - [2023-11-07T16:45:45.822+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ps_etl/ps_etl.py
[2023-11-07T16:45:45.828+0000] {logging_mixin.py:151} INFO - [2023-11-07T16:45:45.827+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ps_etl/ps_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ps_etl/ps_etl.py", line 6, in <module>
    from ps_extract import extract
ModuleNotFoundError: No module named 'ps_extract'
[2023-11-07T16:45:45.829+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ps_etl/ps_etl.py
[2023-11-07T16:45:45.849+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ps_etl/ps_etl.py took 0.033 seconds
[2023-11-07T16:46:15.992+0000] {processor.py:157} INFO - Started process (PID=147) to work on /opt/airflow/dags/ps_etl/ps_etl.py
[2023-11-07T16:46:15.993+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ps_etl/ps_etl.py for tasks to queue
[2023-11-07T16:46:15.996+0000] {logging_mixin.py:151} INFO - [2023-11-07T16:46:15.995+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ps_etl/ps_etl.py
[2023-11-07T16:46:16.004+0000] {logging_mixin.py:151} INFO - [2023-11-07T16:46:16.002+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ps_etl/ps_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ps_etl/ps_etl.py", line 6, in <module>
    from ps_extract import extract
ModuleNotFoundError: No module named 'ps_extract'
[2023-11-07T16:46:16.005+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ps_etl/ps_etl.py
[2023-11-07T16:46:16.025+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ps_etl/ps_etl.py took 0.038 seconds
[2023-11-07T16:46:46.167+0000] {processor.py:157} INFO - Started process (PID=155) to work on /opt/airflow/dags/ps_etl/ps_etl.py
[2023-11-07T16:46:46.168+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ps_etl/ps_etl.py for tasks to queue
[2023-11-07T16:46:46.171+0000] {logging_mixin.py:151} INFO - [2023-11-07T16:46:46.171+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ps_etl/ps_etl.py
[2023-11-07T16:46:46.179+0000] {logging_mixin.py:151} INFO - [2023-11-07T16:46:46.177+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ps_etl/ps_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ps_etl/ps_etl.py", line 6, in <module>
    from ps_extract import extract
ModuleNotFoundError: No module named 'ps_extract'
[2023-11-07T16:46:46.180+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ps_etl/ps_etl.py
[2023-11-07T16:46:46.239+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ps_etl/ps_etl.py took 0.076 seconds
[2023-11-07T16:47:16.330+0000] {processor.py:157} INFO - Started process (PID=163) to work on /opt/airflow/dags/ps_etl/ps_etl.py
[2023-11-07T16:47:16.331+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ps_etl/ps_etl.py for tasks to queue
[2023-11-07T16:47:16.334+0000] {logging_mixin.py:151} INFO - [2023-11-07T16:47:16.334+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ps_etl/ps_etl.py
[2023-11-07T16:47:16.342+0000] {logging_mixin.py:151} INFO - [2023-11-07T16:47:16.341+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ps_etl/ps_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ps_etl/ps_etl.py", line 6, in <module>
    from ps_extract import extract
ModuleNotFoundError: No module named 'ps_extract'
[2023-11-07T16:47:16.343+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ps_etl/ps_etl.py
[2023-11-07T16:47:16.364+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ps_etl/ps_etl.py took 0.038 seconds
[2023-11-07T16:47:46.520+0000] {processor.py:157} INFO - Started process (PID=171) to work on /opt/airflow/dags/ps_etl/ps_etl.py
[2023-11-07T16:47:46.521+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ps_etl/ps_etl.py for tasks to queue
[2023-11-07T16:47:46.524+0000] {logging_mixin.py:151} INFO - [2023-11-07T16:47:46.523+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ps_etl/ps_etl.py
[2023-11-07T16:47:46.530+0000] {logging_mixin.py:151} INFO - [2023-11-07T16:47:46.528+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ps_etl/ps_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ps_etl/ps_etl.py", line 6, in <module>
    from ps_extract import extract
ModuleNotFoundError: No module named 'ps_extract'
[2023-11-07T16:47:46.530+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ps_etl/ps_etl.py
[2023-11-07T16:47:46.548+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ps_etl/ps_etl.py took 0.031 seconds
[2023-11-07T16:48:16.683+0000] {processor.py:157} INFO - Started process (PID=179) to work on /opt/airflow/dags/ps_etl/ps_etl.py
[2023-11-07T16:48:16.684+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ps_etl/ps_etl.py for tasks to queue
[2023-11-07T16:48:16.687+0000] {logging_mixin.py:151} INFO - [2023-11-07T16:48:16.687+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ps_etl/ps_etl.py
[2023-11-07T16:48:16.695+0000] {logging_mixin.py:151} INFO - [2023-11-07T16:48:16.694+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ps_etl/ps_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ps_etl/ps_etl.py", line 6, in <module>
    from ps_extract import extract
ModuleNotFoundError: No module named 'ps_extract'
[2023-11-07T16:48:16.696+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ps_etl/ps_etl.py
[2023-11-07T16:48:16.716+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ps_etl/ps_etl.py took 0.037 seconds
[2023-11-07T16:48:46.907+0000] {processor.py:157} INFO - Started process (PID=187) to work on /opt/airflow/dags/ps_etl/ps_etl.py
[2023-11-07T16:48:46.909+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ps_etl/ps_etl.py for tasks to queue
[2023-11-07T16:48:46.914+0000] {logging_mixin.py:151} INFO - [2023-11-07T16:48:46.914+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ps_etl/ps_etl.py
[2023-11-07T16:48:46.927+0000] {logging_mixin.py:151} INFO - [2023-11-07T16:48:46.925+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ps_etl/ps_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ps_etl/ps_etl.py", line 6, in <module>
    from ps_extract import extract
ModuleNotFoundError: No module named 'ps_extract'
[2023-11-07T16:48:46.938+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ps_etl/ps_etl.py
[2023-11-07T16:48:46.967+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ps_etl/ps_etl.py took 0.066 seconds
[2023-11-07T16:49:17.179+0000] {processor.py:157} INFO - Started process (PID=195) to work on /opt/airflow/dags/ps_etl/ps_etl.py
[2023-11-07T16:49:17.180+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ps_etl/ps_etl.py for tasks to queue
[2023-11-07T16:49:17.183+0000] {logging_mixin.py:151} INFO - [2023-11-07T16:49:17.182+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ps_etl/ps_etl.py
[2023-11-07T16:49:17.189+0000] {logging_mixin.py:151} INFO - [2023-11-07T16:49:17.188+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ps_etl/ps_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ps_etl/ps_etl.py", line 6, in <module>
    from ps_extract import extract
ModuleNotFoundError: No module named 'ps_extract'
[2023-11-07T16:49:17.190+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ps_etl/ps_etl.py
[2023-11-07T16:49:17.207+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ps_etl/ps_etl.py took 0.030 seconds
[2023-11-07T16:49:47.378+0000] {processor.py:157} INFO - Started process (PID=203) to work on /opt/airflow/dags/ps_etl/ps_etl.py
[2023-11-07T16:49:47.379+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ps_etl/ps_etl.py for tasks to queue
[2023-11-07T16:49:47.382+0000] {logging_mixin.py:151} INFO - [2023-11-07T16:49:47.382+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ps_etl/ps_etl.py
[2023-11-07T16:49:47.390+0000] {logging_mixin.py:151} INFO - [2023-11-07T16:49:47.389+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ps_etl/ps_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ps_etl/ps_etl.py", line 6, in <module>
    from ps_extract import extract
ModuleNotFoundError: No module named 'ps_extract'
[2023-11-07T16:49:47.391+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ps_etl/ps_etl.py
[2023-11-07T16:49:47.410+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ps_etl/ps_etl.py took 0.036 seconds
[2023-11-07T16:50:17.536+0000] {processor.py:157} INFO - Started process (PID=211) to work on /opt/airflow/dags/ps_etl/ps_etl.py
[2023-11-07T16:50:17.538+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ps_etl/ps_etl.py for tasks to queue
[2023-11-07T16:50:17.540+0000] {logging_mixin.py:151} INFO - [2023-11-07T16:50:17.540+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ps_etl/ps_etl.py
[2023-11-07T16:50:17.549+0000] {logging_mixin.py:151} INFO - [2023-11-07T16:50:17.547+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ps_etl/ps_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ps_etl/ps_etl.py", line 6, in <module>
    from ps_extract import extract
ModuleNotFoundError: No module named 'ps_extract'
[2023-11-07T16:50:17.550+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ps_etl/ps_etl.py
[2023-11-07T16:50:17.578+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ps_etl/ps_etl.py took 0.047 seconds
[2023-11-07T16:50:47.688+0000] {processor.py:157} INFO - Started process (PID=219) to work on /opt/airflow/dags/ps_etl/ps_etl.py
[2023-11-07T16:50:47.689+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ps_etl/ps_etl.py for tasks to queue
[2023-11-07T16:50:47.692+0000] {logging_mixin.py:151} INFO - [2023-11-07T16:50:47.692+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ps_etl/ps_etl.py
[2023-11-07T16:50:47.700+0000] {logging_mixin.py:151} INFO - [2023-11-07T16:50:47.698+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ps_etl/ps_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ps_etl/ps_etl.py", line 6, in <module>
    from ps_extract import extract
ModuleNotFoundError: No module named 'ps_extract'
[2023-11-07T16:50:47.701+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ps_etl/ps_etl.py
[2023-11-07T16:50:47.721+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ps_etl/ps_etl.py took 0.037 seconds
[2023-11-07T16:51:17.869+0000] {processor.py:157} INFO - Started process (PID=227) to work on /opt/airflow/dags/ps_etl/ps_etl.py
[2023-11-07T16:51:17.870+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ps_etl/ps_etl.py for tasks to queue
[2023-11-07T16:51:17.872+0000] {logging_mixin.py:151} INFO - [2023-11-07T16:51:17.872+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ps_etl/ps_etl.py
[2023-11-07T16:51:17.879+0000] {logging_mixin.py:151} INFO - [2023-11-07T16:51:17.877+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ps_etl/ps_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ps_etl/ps_etl.py", line 6, in <module>
    from ps_extract import extract
ModuleNotFoundError: No module named 'ps_extract'
[2023-11-07T16:51:17.879+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ps_etl/ps_etl.py
[2023-11-07T16:51:17.897+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ps_etl/ps_etl.py took 0.031 seconds
[2023-11-07T16:51:48.044+0000] {processor.py:157} INFO - Started process (PID=235) to work on /opt/airflow/dags/ps_etl/ps_etl.py
[2023-11-07T16:51:48.045+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ps_etl/ps_etl.py for tasks to queue
[2023-11-07T16:51:48.048+0000] {logging_mixin.py:151} INFO - [2023-11-07T16:51:48.047+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ps_etl/ps_etl.py
[2023-11-07T16:51:48.054+0000] {logging_mixin.py:151} INFO - [2023-11-07T16:51:48.053+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ps_etl/ps_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ps_etl/ps_etl.py", line 6, in <module>
    from ps_extract import extract
ModuleNotFoundError: No module named 'ps_extract'
[2023-11-07T16:51:48.055+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ps_etl/ps_etl.py
[2023-11-07T16:51:48.073+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ps_etl/ps_etl.py took 0.033 seconds
[2023-11-07T16:52:18.212+0000] {processor.py:157} INFO - Started process (PID=243) to work on /opt/airflow/dags/ps_etl/ps_etl.py
[2023-11-07T16:52:18.213+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ps_etl/ps_etl.py for tasks to queue
[2023-11-07T16:52:18.216+0000] {logging_mixin.py:151} INFO - [2023-11-07T16:52:18.216+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ps_etl/ps_etl.py
[2023-11-07T16:52:18.224+0000] {logging_mixin.py:151} INFO - [2023-11-07T16:52:18.222+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ps_etl/ps_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ps_etl/ps_etl.py", line 6, in <module>
    from ps_extract import extract
ModuleNotFoundError: No module named 'ps_extract'
[2023-11-07T16:52:18.225+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ps_etl/ps_etl.py
[2023-11-07T16:52:18.247+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ps_etl/ps_etl.py took 0.039 seconds
[2023-11-07T16:52:48.371+0000] {processor.py:157} INFO - Started process (PID=251) to work on /opt/airflow/dags/ps_etl/ps_etl.py
[2023-11-07T16:52:48.371+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ps_etl/ps_etl.py for tasks to queue
[2023-11-07T16:52:48.374+0000] {logging_mixin.py:151} INFO - [2023-11-07T16:52:48.374+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ps_etl/ps_etl.py
[2023-11-07T16:52:48.380+0000] {logging_mixin.py:151} INFO - [2023-11-07T16:52:48.379+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ps_etl/ps_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ps_etl/ps_etl.py", line 6, in <module>
    from ps_extract import extract
ModuleNotFoundError: No module named 'ps_extract'
[2023-11-07T16:52:48.381+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ps_etl/ps_etl.py
[2023-11-07T16:52:48.399+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ps_etl/ps_etl.py took 0.031 seconds
[2023-11-07T16:53:18.539+0000] {processor.py:157} INFO - Started process (PID=259) to work on /opt/airflow/dags/ps_etl/ps_etl.py
[2023-11-07T16:53:18.540+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ps_etl/ps_etl.py for tasks to queue
[2023-11-07T16:53:18.544+0000] {logging_mixin.py:151} INFO - [2023-11-07T16:53:18.544+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/ps_etl/ps_etl.py
[2023-11-07T16:53:18.555+0000] {logging_mixin.py:151} INFO - [2023-11-07T16:53:18.553+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/ps_etl/ps_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ps_etl/ps_etl.py", line 6, in <module>
    from ps_extract import extract
ModuleNotFoundError: No module named 'ps_extract'
[2023-11-07T16:53:18.556+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ps_etl/ps_etl.py
[2023-11-07T16:53:18.614+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ps_etl/ps_etl.py took 0.078 seconds
