[2023-11-07T04:47:40.376+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ps_etl.load_to_snowflake_table manual__2023-11-07T04:47:29.601090+00:00 [queued]>
[2023-11-07T04:47:40.385+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ps_etl.load_to_snowflake_table manual__2023-11-07T04:47:29.601090+00:00 [queued]>
[2023-11-07T04:47:40.386+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-11-07T04:47:40.397+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): load_to_snowflake_table> on 2023-11-07 04:47:29.601090+00:00
[2023-11-07T04:47:40.403+0000] {standard_task_runner.py:57} INFO - Started process 2182 to run task
[2023-11-07T04:47:40.409+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'ps_etl', 'load_to_snowflake_table', 'manual__2023-11-07T04:47:29.601090+00:00', '--job-id', '91', '--raw', '--subdir', 'DAGS_FOLDER/ps_etl.py', '--cfg-path', '/tmp/tmpvztlun74']
[2023-11-07T04:47:40.413+0000] {standard_task_runner.py:85} INFO - Job 91: Subtask load_to_snowflake_table
[2023-11-07T04:47:40.468+0000] {task_command.py:416} INFO - Running <TaskInstance: ps_etl.load_to_snowflake_table manual__2023-11-07T04:47:29.601090+00:00 [running]> on host d2308b8de1b3
[2023-11-07T04:47:40.590+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ps_etl' AIRFLOW_CTX_TASK_ID='load_to_snowflake_table' AIRFLOW_CTX_EXECUTION_DATE='2023-11-07T04:47:29.601090+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-07T04:47:29.601090+00:00'
[2023-11-07T04:47:40.607+0000] {base.py:73} INFO - Using connection ID 'snowflake_default' for task execution.
[2023-11-07T04:47:40.609+0000] {connection.py:329} INFO - Snowflake Connector for Python Version: 3.2.1, Python Version: 3.8.18, Platform: Linux-6.4.16-linuxkit-x86_64-with-glibc2.2.5
[2023-11-07T04:47:40.610+0000] {connection.py:1069} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2023-11-07T04:47:40.611+0000] {connection.py:1087} INFO - Setting use_openssl_only mode to False
[2023-11-07T04:47:41.364+0000] {cursor.py:804} INFO - query: [ALTER SESSION SET autocommit=False]
[2023-11-07T04:47:41.514+0000] {cursor.py:817} INFO - query execution done
[2023-11-07T04:47:41.515+0000] {cursor.py:959} INFO - Number of results in first chunk: 1
[2023-11-07T04:47:41.515+0000] {sql.py:418} INFO - Running statement: USE SCHEMA PUBLIC;, parameters: None
[2023-11-07T04:47:41.515+0000] {cursor.py:804} INFO - query: [USE SCHEMA PUBLIC;]
[2023-11-07T04:47:41.666+0000] {cursor.py:817} INFO - query execution done
[2023-11-07T04:47:41.666+0000] {cursor.py:959} INFO - Number of results in first chunk: 1
[2023-11-07T04:47:41.667+0000] {sql.py:427} INFO - Rows affected: 1
[2023-11-07T04:47:41.667+0000] {snowflake.py:400} INFO - Rows affected: 1
[2023-11-07T04:47:41.667+0000] {snowflake.py:401} INFO - Snowflake query id: 01b0299f-0004-d114-0000-0001ead783c1
[2023-11-07T04:47:41.668+0000] {sql.py:418} INFO - Running statement: CREATE OR REPLACE TABLE LOYALTY_EARNED_HOURLY (
            date TIMESTAMP,
            userId VARCHAR(20),
            country CHAR(2),
            total_lp_earned INT
         );, parameters: None
[2023-11-07T04:47:41.668+0000] {cursor.py:804} INFO - query: [CREATE OR REPLACE TABLE LOYALTY_EARNED_HOURLY ( date TIMESTAMP, userId VARCHAR(2...]
[2023-11-07T04:47:41.941+0000] {cursor.py:817} INFO - query execution done
[2023-11-07T04:47:41.941+0000] {cursor.py:959} INFO - Number of results in first chunk: 1
[2023-11-07T04:47:41.942+0000] {sql.py:427} INFO - Rows affected: 1
[2023-11-07T04:47:41.944+0000] {snowflake.py:400} INFO - Rows affected: 1
[2023-11-07T04:47:41.944+0000] {snowflake.py:401} INFO - Snowflake query id: 01b0299f-0004-d17f-0000-0001ead72345
[2023-11-07T04:47:41.945+0000] {sql.py:418} INFO - Running statement: CREATE OR REPLACE TABLE PURCHASES (
            date TIMESTAMP,
            userId VARCHAR(20),
            price_in_usd DECIMAL(10, 2),
            transaction_id UUID
         );, parameters: None
[2023-11-07T04:47:41.945+0000] {cursor.py:804} INFO - query: [CREATE OR REPLACE TABLE PURCHASES ( date TIMESTAMP, userId VARCHAR(20), price_in...]
[2023-11-07T04:47:42.100+0000] {cursor.py:817} INFO - query execution done
[2023-11-07T04:47:42.107+0000] {connection.py:659} INFO - closed
[2023-11-07T04:47:42.204+0000] {connection.py:665} INFO - No async queries seem to be running, deleting session
[2023-11-07T04:47:42.310+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ps_load.py", line 37, in run_snowflake_load_sql
    snowflake_hook.run(create_table_command)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 388, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 423, in _run_command
    cur.execute(sql_statement)
  File "/home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/cursor.py", line 908, in execute
    Error.errorhandler_wrapper(self.connection, self, error_class, errvalue)
  File "/home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/errors.py", line 290, in errorhandler_wrapper
    handed_over = Error.hand_to_other_handler(
  File "/home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/errors.py", line 345, in hand_to_other_handler
    cursor.errorhandler(connection, cursor, error_class, error_value)
  File "/home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/errors.py", line 221, in default_errorhandler
    raise error_class(
snowflake.connector.errors.ProgrammingError: 002040 (42601): 01b0299f-0004-d180-0000-0001ead7b099: SQL compilation error:
Unsupported data type 'UUID'.
[2023-11-07T04:47:42.322+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=ps_etl, task_id=load_to_snowflake_table, execution_date=20231107T044729, start_date=20231107T044740, end_date=20231107T044742
[2023-11-07T04:47:42.338+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 91 for task load_to_snowflake_table (002040 (42601): 01b0299f-0004-d180-0000-0001ead7b099: SQL compilation error:
Unsupported data type 'UUID'.; 2182)
[2023-11-07T04:47:42.352+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-07T04:47:42.369+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
